apiVersion: v1
kind: Service
metadata:
  name: sdn-controller-service
spec:
  type: NodePort
  selector:
    app: sdn-controller
    component: connection-manager
  ports:
    - name: openflow
      port: 6633
      targetPort: 6633
      nodePort: 30080
    - name: grpc
      port: 8094
      targetPort: 8094
---
apiVersion: v1
kind: Service
metadata:
  name: flowadd-service
spec:
  type: ClusterIP
  selector:
    app: sdn-controller
    component: flowadd
  ports:
    - port: 8092
      targetPort: 8092
---
apiVersion: v1
kind: Service
metadata:
  name: packet-handler-service
spec:
  type: ClusterIP
  selector:
    app: sdn-controller
    component: packet-handler
  ports:
    - port: 8090
      targetPort: 8090